project: 2025-11-12_world-ride_v01
runtime_seconds: 15
aspect_ratio: 16x9
frame_rate: 24
stylepacks:
  - real_cinema
  - sci_fi_realism
seed: 148921
bpm: 96
bloom_peak: 0.6
audio_sync_threshold_db: -12
notes:
  - 初版腳本對照 scene_block 模板填寫
  - 後續版本沿用命名規則 v02/v03
