project: 2025-02-15_frost-shard-volley_v01
runtime_seconds: 15
aspect_ratio: 16x9
frame_rate: 24
stylepacks:
  - real_cinema
  - fantasy_glacier
seed: 274305
bpm: 78
bloom_peak: 0.4
audio_sync_threshold_db: -10
notes:
  - 0-5s 鎖定；5-10s 貝茲弧矢；10-15s 凍爆
  - 需測試 GPU 粒子結晶化效率
